### PR TITLE
Changed from old authentication to token based authentication

### PR DESCRIPTION
**Pull request by hitechdk**

### CODE REVIEW

**Comment by tkjaergaard** [comment]
Thank you for the PR! :+1: 

I do not completely agree with overriding the whole connect/authentication layer with the `connectWithToken` method, since `connect` still ain't completely deprecated and such a modification will cause breaking changes and i'm not nearly ready to release a 3.0 version.

I might take a look at simplifying the API so both authentication options becomes available, i think we have to do it that way for now.

**Comment by danielboendergaard** [comment]
The header must be added before March 15th 2016 :)
http://techtalk.e-conomic.com/new-deadline-for-x-economicappidentier-http-header/

**Comment by nikolajlovenhardt** [comment]
Ping @tkjaergaard

**Comment by canfiax** [comment]
I'd love to see this PR implemented as well!

**Comment by tkjaergaard** [comment]
@hitechdk @danielboendergaard @nikolajlovenhardt @canfiax 

Just pushed version 2.0.4 which includes a new TokenClient class.

See the docs here: https://github.com/tkjaergaard/Economic-PHP-SDK/blob/master/docs/GettingStarted.md

**Comment by benzon** [comment]
I know this is old, but there is no reason to keep the old Client around even if you are not ready with a version 3.0, it's been 2 years now almost since this post was added, and the headers are a must now for the old Client method.

So with out doubt the new TokenClient should be the only way to auth.

**Pull request closed without merging**
