### PR TITLE
Adding debtor bulk update method.

### PR DESCRIPTION
**Pull request by Svenn1**
This is a good base for an update debitor method + update contact info and ean.

You might want to edit this a little bit to be more universal, but it's a good start <3

With regards, Napp.

### CODE REVIEW

**Comment by tkjaergaard** [comment]
Hi @Svenn1,

Thank you for your PR :+1:

**Comment by tkjaergaard** [comment]
Hi @Svenn1,

Thank you for your PR :+1:

**Comment by Svenn1** [comment]
You are welcome ! :)

**Comment by Svenn1** [comment]
I would recommend refining the update method though, it's still a bit rough! .. I would do it myself but Napp is keeping me busy busy busy ^^

**Pull request merged**
