### PR TITLE
Suggestions, update and bug fix

### PR DESCRIPTION
**Pull request by Diblo**

### CODE REVIEW

**Comment by Diblo** [comment]
BUG FIX:
* Correct namespace

UPDATE:
* Update Debtors.md

SUGGESTIONS:
* Added new method (This method makes it possible to retrieve a particular currency price on a product)
* Update Product.php
* A class to handle price groups (This is a class to handel PriceGroup_*)
* Comment corrections (There is more flaws in the descriptions of the variable types. I hope it's okay that I fixes the flaws when I notices them)

**Comment by tkjaergaard** [comment]
Hi Diblo,

Thank you for another pull request. The Namespace is off in PriceGroup.php and the rest of your additions is missing documentation.

Fix those issues and I'll merge right away :)

**Comment by Diblo** [comment]
What type of documentation are you thinking on, md (manual), comments in the code etc? :)

**Comment by Diblo** [comment]
Commit a258cefacb8cc7b78a20abdff9b39e2f29d12c8b (`Update Debtors.md`) is a update of the section `[...] search Debtors by a specific field.` I added the option PARTIALNAME (Partial Name), and changed the other options to suit the values given to the method `search` as agreement (`$by`).

Commit 0c1d27e55771ed32fcc8e56d460f56f50de388e4 (`Added new method`) I have added the method `getPriceByCurrency` to get the price of a product in a particular currency. The method takes two arguments: product number and currency code - Currency codes: DKK, USD, EUR etc.
\- See [ProductPrice_GetPrice](https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=ProductPrice_GetPrice)

Commit 411d4ea0698cfcf57ecf0f04753fd07837559c2f  (`Update Product.php`) is an update to commit 0c1d27e55771ed32fcc8e56d460f56f50de388e4 (`Added new method`). It improves the method description so it's easier to understand the purpose of the method. 

Commit 3502aee0a9053e40320eda70a2a14d20f0e3f1c2 (`A class to handle price groups`) is a new class to handle `PriceGroup_*`. The price groupe is a way to make special prices on products.
The file `PriceGroup.php` have a class `PriceGroup` with a `__construct` to handle client reference and two metodes `all` and `getPrice`.
- Metode `all` takes no arguments and returns an array with the price groups numbers. 
- Metode `getPrice` takes two arguments, price group number and product number, and returns the special price of the product. If no special price is found then the sales price is returned instead.

\- See [PriceGroup_GetAll](https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=PriceGroup_GetAll) and [PriceGroup_GetPrice](https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=PriceGroup_GetPrice)

Commit 03d2e8d5127b50e5c2f96a935faf8870216e4247 (`Comment corrections`)
- Some variable names was misspelled in method description - `$QuotationLineHandle` -> `$orderLineHandle`.
- The `qty` method description told that the argument `$qty` should be an integer, but it should be a float. The reason for this is it may be numbers of working hours there are given as argument - 1.5 hours.
   - See also [OrderLine_SetQuantity](https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=OrderLine_SetQuantity) and [phpDocumentor Primitives](http://www.phpdoc.org/docs/latest/guides/types.html#primitives)
- The `product` method description told that the argument `$product` should be an integer, but it should be a string. The reason for this is that product numbers/ids can be anything - 18372, AT-10001, B-FWHC15 etc.
   - See also [Product_FindByNumber](https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=Product_FindByNumber)

Commit b1ec15f3728d7f91bc0b647cd946de236dd2bd4c (`Correct namespace`) is an update to commit 0c1d27e55771ed32fcc8e56d460f56f50de388e4 (`Added new method`) and bugfix. It updates the namespace in PriceGroup.php file. While check the namespace I found a misspelled namespace in `Subscription.php` file - `namespace Tkj\Economics\Subscriptions`.

**Comment by tkjaergaard** [comment]
Thank you for the PR, sorry for the delay on merging it. Keep up the good work :+1:

**Comment by tkjaergaard** [comment]
@Diblo could you write some documentation for the new methods and classes in the **docs section**. I'll tag the repo for 2.0.2 when done :+1:

**Comment by Diblo** [comment]
Yep, I will look at it :-)

**Comment by Oliwicked** [comment]
Im new here, but stumpled upon a missing case for phone number in debtor -> update() :)
 case 'phone':
                    $this->client
                        ->Debtor_SetTelephoneAndFaxNumber($request);
                    break;

**Comment by Diblo** [comment]
@Oliwicked, @tkjaergaard I implement this option in the next PR. But it may take a few months to complete next PR.

**Pull request merged**
